### ISSUE TITLE
Package fails upon import when using webpack

### ISSUE THREAD

**Issue by johndanek** [videojs/videojs-flash#9]
My project uses webpack + babel for loading node_modules.

In my project's index.js, I call `import flash from 'videojs-flash';`

Webpack then fails, pointing to this line: https://github.com/videojs/videojs-flash/blob/master/src/index.js#L88

This is the error:
`ERROR in ./~/videojs-swf/package.json
Module parse failed: /Users/user/projects/myproject/node_modules/videojs-swf/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (/Users/user/projects/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/user/projects/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/user/projects/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/user/projects/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/user/projects/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/user/projects/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/user/projects/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/user/projects/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/user/projects/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/user/projects/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/user/projects/myproject/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/user/projects/myproject/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/user/projects/myproject/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/user/projects/myproject/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/user/projects/myproject/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.provide (/Users/user/projects/myproject/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
 @ ./~/videojs-flash/es5/index.js 113:16-51`

You will probably need more info from me (unfortunately I'm not a webpack expert, but I'll try as best I can)

**Comment by gkatsev** [comment]
Fixed in RC2

**Comment by sulphur** [comment]
i have the same error today. I'm using all the latest versions
